[package]
name = "bothstr"
version = "0.1.0"
authors = ["Amos Wenger <amoswenger@gmail.com>"]
edition = "2018"

[dependencies]
smol_str = "0.1.15"
smartstring = "0.2.1"
criterion = "0.3.3"
rand = "0.7.3"

[[bench]]
name = "string_bench"
harness = false
